/*
 * Farm Management REST WS
 * The web service layer.
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.packt.springboot22.vid02.config.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
