/*
 * Farm Management REST WS
 * The web service layer.
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.packt.springboot22.vid02.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Carries Personal and Login Data
 */
@ApiModel(description = "Carries Personal and Login Data")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-01T10:47:23.730+08:00")
public class ProfileInformation {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("mobile")
  private String mobile = null;

  @JsonProperty("address")
  private String address = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("approved")
  private Boolean approved = null;

  public ProfileInformation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Complete name
   * @return name
  **/
  @ApiModelProperty(value = "Complete name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProfileInformation mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Mobile Number
   * @return mobile
  **/
  @ApiModelProperty(value = "Mobile Number")
  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public ProfileInformation address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Complete Address
   * @return address
  **/
  @ApiModelProperty(value = "Complete Address")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public ProfileInformation email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Current email address
   * @return email
  **/
  @ApiModelProperty(value = "Current email address")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ProfileInformation username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Username/Email
   * @return username
  **/
  @ApiModelProperty(value = "Username/Email")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public ProfileInformation password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Strong Password
   * @return password
  **/
  @ApiModelProperty(value = "Strong Password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public ProfileInformation approved(Boolean approved) {
    this.approved = approved;
    return this;
  }

   /**
   * Admin&#39;s Approval
   * @return approved
  **/
  @ApiModelProperty(value = "Admin's Approval")
  public Boolean isApproved() {
    return approved;
  }

  public void setApproved(Boolean approved) {
    this.approved = approved;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileInformation profileInformation = (ProfileInformation) o;
    return Objects.equals(this.name, profileInformation.name) &&
        Objects.equals(this.mobile, profileInformation.mobile) &&
        Objects.equals(this.address, profileInformation.address) &&
        Objects.equals(this.email, profileInformation.email) &&
        Objects.equals(this.username, profileInformation.username) &&
        Objects.equals(this.password, profileInformation.password) &&
        Objects.equals(this.approved, profileInformation.approved);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, mobile, address, email, username, password, approved);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileInformation {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

